alang=japanese,jap,jp,korean,kor,kr,ko,english,eng,en,gb,any,yes
slang=turkish,türkçe,tur,tr,english,eng,en,gb,japanese,jap,jp,dialogue,any,yes
osd-color=#555555
osd-on-seek=msg
osd-duration=500
osd-font='Victor Mono'
keepaspect-window=no
geometry=50%x50%
demuxer-max-bytes=500000KiB
demuxer-max-back-bytes=500000KiB
save-position-on-quit=yes